travis:
  secure:
    BINSTAR_TOKEN: PfW2GsLJCM12CI72aD2jzOJAl8XQlt7Tx9qwhJj03TX+yIq2Z+EWrsVy+YItfDyE7SLEXe8iIpQU5Q7JKNBJwR8imAHtWXXuAdl7Z5/f80rMSIJ1nJOq0FF4EVNMwdA2F1wLbCJvQmuZ1fZ0AV89PxzjCADbQCBqucJ4yEEbENdZditGBqPm7JttRMJxdllKfQZu2CyCT8CvG2Dt/+Oa1P03gBvz44l4L62KXsgVkvDZpEU3lQD64jcbQqo4s4+BKIMcWIOvfF70jxAZ4dUN0LCOpuUL3k2INlRktZmMN7E1OGNelw0e8tvms2Bux81sAlbsO5QkWZg7e3vM4wzN16cRR8JkISu+rkeqSvSl0k05x1JEsEAtnbki2U0HXXamIsb6QJ0VlbZpx1sH6+/YePT1A/FTNdeNgZsDiRzqDY3JvKT8WtwhdNWUVnOW1awxZx/X48vu4fmZx0pSw7JtDWtJMp1frQL/LLZAQsq9I728G9P6e0nil/5NTFamFC7sNxCrGSAniGbaj7xJwhidiPx0fpkpYTNthq+FDyAupW44pCNztSI+IfO4s0ta48G0gNez2j0XjXPeMjGnUfhLn0utiSMOY28PmGnUSb7sTLM3NMeGe+RR4nSpKiCKP0f7L9Srx6K/+m25WOb/SGHPrvX9tg+g9H5/9CLL7zlA1C0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
